services:
  app:
    image: phonebook-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: phone_database
    volumes:
      - ./backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: phonebook-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - MONGODB_URI=mongodb://the_username:the_password@mongo:27017/phone_database
      - PORT=3001
    depends_on:
      - mongo

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app
      - server

volumes:
  mongo_data:
